### ISSUE TITLE
Documentation Reference is utterly broken/missing since class conversion

### ISSUE THREAD

**Issue by ericblade** [ericblade/mws-advanced#107]
It looks like the documentation auto generator doesn't handle classes very well, if at all, or needs some kind of special support to do so.  Nothing from the MwsAdvanced class is documented, only from the helpers / parsers.  Oops?!

Maybe need to find a new generator.

**Comment by nojacko** [comment]
+1 for more documentation. 

I was having the problem of checking to see if this this library supported a certain endpoint. Couldn't find it and couldn't find either `getMarketplaces ` and `callEndpoint` functions in documentation. Both are mentioned in the Getting Started pages.

**Comment by ericblade** [comment]
My bad for not noticing what disappeared from the doc after the last change. I may need to move the doc reference around. For some reason the doc parser is completely ignoring most of lib/index, which is where you can find the function docs that are missing right now.

**Comment by ericblade** [comment]
.. what functionality are you looking for?

**Comment by ericblade** [comment]
sorry, was on mobile, and couldn't tag.  @nojacko Technically :-D you can call any MWS API with this lib, although it has wrappers for most of the /Products, /Orders, /Reports, and a few other functions currently that try to make more sense out of the data than what comes back from a regular xml2json conversion.  What specifically are you looking for?  If it's not there, it might be pretty quick to implement, I may just haven't got to it because of not needing it.

**Comment by ericblade** [comment]
alright, we need to find a new documentation parser. will file new task for that
