### ISSUE TITLE
listFinancialEvents parameter validation: what is FinancialEventGroupId ?

### ISSUE THREAD

**Issue by ericblade** [ericblade/mws-advanced#13]
MWS documentation indicates it is "any valid financial event group identifier". What is that? Where do we find those?
We should find it, and implement it.

**Comment by aflansburg** [comment]
I'm looking into this currently - it looks like events might be settlments/payments, etc. and teh FinancialEventGroupId something given as a response to ListFinancialEventGroups. So I'm assuming you'd have to implement that first to determine those group Ids.

**Comment by chatlourd** [comment]
Any luck finding out what the "FinancialEventGroupId"s are ?

**Comment by ericblade** [comment]
so, i had originally wrote this when I was just doing like stream of conscious notes for things that would be good to know.

ListFinancialEventGroups returns a List of FinancialEventGroup, and FinancialEventGroupId is a field contained within FinancialEventGroup.

I think initially I was under the impression that Group might've been a *type* of Financial Event, but it appears to be more a group of events over a specific time period (probably the standard 2-week pay period?)

Here's the doc for the FinancialEventGroup datatype:
https://docs.developer.amazonservices.com/en_US/finances/Finances_Datatypes.html#FinancialEventGroup

According to that, FinancialEventGroupId is an xs:string.  I guess I'd have to make a few calls to ListFinancialEventGroups to see if there's any particular format to the xs:string that could be validated.

I think since whatever is supposed to be given to this parameter is something that comes from the ListFinancialEventGroups call, I'm going to close this, as I think this is enough research, and I don't see a validator being particularly necessary.

**Comment by chatlourd** [comment]
Thx for the explanation. I finally figured it out.

 

I’m trying to get all the financial data for the last 6 months but ,while I seem to be able to do that in the scratchpad quite easily, when I query the API (in python) it seems to be returning random events and groups which make no sense whether I select a groupid or an event after a certain date. 

 

Did you manage to make any sense of it ?

**Comment by ericblade** [comment]
I did not explore doing that using the live API, but something that might be easier for past time is to grab the automatically generated report ````_GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_````.  You can grab that for quite a while back, and I suspect it would have whatever info you're looking for.
