### ISSUE TITLE
forceArray always makes a shallow copy

### ISSUE THREAD

**Issue by pwrnrd** [ericblade/mws-advanced#155]
`forceArray()` always make a shallow copy of an array. Since some responses might contain a lot of nested elements which should be forced to be an array, shallow copying can become memory intensive. Hence, I'd like to propose that we don't shallow copy elements which are already arrays, but simple return that array from `forceArray()`. E.g.:

```
const forceArray = (arr) => (Array.isArray(arr) ? arr : [].concat(arr !== undefined ? arr : []));
```

However this change brakes the following test:

```
        it('returns a copy of array passed in', () => {
            const x = ['test1', 'test2'];
            const y = forceArray(x);
            expect(y).to.not.equal(x);
            expect(y).to.deep.equal(x);
            return true;
        });
```
Since this test is failing, I'm not sure whether I can make this change without causing the code to break somewhere.  Other tests still pass. Therefore, I'm in doubt whether we really use the shallow copy properties in our code. So I'm not uncertain whether the test case above actually reflects an implementation requirement. 

Is it ok for me to change the test case and implement my proposed change?

**Comment by ericblade** [comment]
I can't think of any reason that we need to copy them, so that seems perfectly reasonable.

**Comment by pwrnrd** [comment]
I'll do that! Thanks.
