### ISSUE TITLE
Marketplace API Endpoint (Marketplace ID)

### ISSUE THREAD

**Issue by nicolasbettag** [ericblade/mws-advanced#19]
Hi there,

where can I define, which marketplace the tool should use?
In Germany, the API endpoint must be [mws.amazonservices.de](mws.amazonservices.de), otherwise you'll get an `Error: 401 Unauthorized - AccessDenied`.

**Comment by ericblade** [comment]
Hi! The underlying mws-simple API supports a host parameter, that I only just recently became aware of. I'm away from code right now, but if you add a parameter to index::init() to pass host to mws, then it should work, and I'd be happy to accept a pull request for that if you get to it before I get back in several hours.

**Comment by ericblade** [comment]
I just did a little digging, and discovered this document that lists all the currently available hosts and marketplaceIds: https://docs.developer.amazonservices.com/en_US/dev_guide/DG_Endpoints.html

I'm thinking in addition to supplying overrides for host/port, just on the offchance anyone ever needs to do that, we should supply the endpoints and marketIds in the constants.js, and auto-select if the host/port isn't overridden by the user.

**Comment by ericblade** [comment]
hey @nicolasbettag I got to it first :-)  I've passed through the 'host' and 'port' parameters, so those can be overridden to anything, and also added a region parameter to init(), so init({ region: 'EU' }) should work as well as init({ host: mws-eu.amazonservices.com }) .. i note that mws.amazonservices.de is not in the MWS documentation list, so I'm guessing that it's aliased to mws-eu.amazonservices.com
