### ISSUE TITLE
Discussion/Q&A: JS version, Node version, -harmony

### ISSUE THREAD

**Issue by aflansburg** [ericblade/mws-advanced#6]
I must admit, I'm a bit new to working on a project such as this with other people - so I'm equally as excited, but I did have a couple of questions. As far as JS (ECMAScript) version - I'm assuming ES6. I'm currently running Node 8.9.0 and haven't had issues, but I am completely clueless regarding the '-harmony' switch and finding info on it has been difficult and what I have found was slightly confusing. 

Also - I ditched the README edit PR since you mentioned some overall changes needed to be made there anyways - I meant to include the Promise post-action (.then, .catch) when I originally suggested edits, but forgot and wasn't sure how active the project was!

**Comment by ericblade** [comment]
For many versions now, node has hidden the newest features that aren't guaranteed to work right behind a command line switch, --harmony .  When I started in node 8.5 or 8.6, I think, both async/await and object destructuring required it to work.  I think both are supported without it now.   I prefer using the newest things, without regard for running in older versions -- people who want to do that can setup their own build chain to convert it to ES5 or whatever :)

Feel free to re-submit any changes that you think would make it more clear, I'm hitting a year end "crunch time" at work, so as much as I recognize that the README is not nearly as readable as I thought it was when I wrote it, it's not likely that I'm going to get to making any changes.

**Comment by aflansburg** [comment]
Sounds good - I'm still familiarizing myself with the project so I appreciate the info. From what I'm seeing Node 8.9.0 seems to address anything that the -harmony switch enabled. Glad to hear ES6 - I really started my learning of JS and Node with ES6 so it's actually more difficult to go backwards....
