### ISSUE TITLE
listOrderItems TypeError

### ISSUE THREAD

**Issue by pwrnrd** [ericblade/mws-advanced#91]
I'm trying to load the products that belogn to a certain order using listOrderItems. For most orders the function listOrderItems seems to work. However, in some cases, I get the following error:

````
TypeError: Cannot read property  'numberOfItems' of undefined
     at transformIntsAndBools (parsers/orderItems.js:40:9)
````

The function:

````

function transformIntsAndBools(item) {
    const {
        quantityOrdered,
        quantityShipped,
        isGift,
        productInfo,
        ...restItem
    } = item;
    const {
        numberOfItems,
        ...restProductInfo
    } = productInfo;

    return {
        ...restItem,
        isGift: stringToBool(isGift),
        quantityOrdered: stringToInt(quantityOrdered),
        quantityShipped: stringToInt(quantityShipped),
        productInfo: {
            ...restProductInfo,
            numberOfItems: stringToInt(numberOfItems),
        },
    };
}
`````
How could I fix this?

**Comment by ericblade** [comment]
well, I didn't know you could do this until just now, but it appears you can use default syntax in destructuring:

````
const {
    ....
    productInfo = {},
    ....
} = item;
````
seems to default productInfo to an empty object, if there isn't one.

If there isn't a productInfo attached to the order, there might be other assumptions that also fail.  

Perhaps you could do a ````listOrderItems(yourOptions, { saveRaw: './raw.json', saveParsed: './parsed.json' })```` on a specific order that is breaking it, so we can see why an order wouldn't have a productInfo ? perhaps it is a cancelled or pending order?  or we're breaking the data somewhere else? i'm not sure.
